version: "3.7"

services:
  db:
    image: "postgres:15-alpine"
    container_name: senpro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: senpro_db
      POSTGRES_PASSWORD: senpro
      POSTGRES_USER: senpro
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - senpro-network

networks:
  senpro-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
